// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3eJAa7cW3C5lsxWalUf0XMFcXqcboZvw',
    appId: '1:431590081010:web:03808b67872dd20e426b6b',
    messagingSenderId: '431590081010',
    projectId: 'lawyer-up-40365',
    authDomain: 'lawyer-up-40365.firebaseapp.com',
    storageBucket: 'lawyer-up-40365.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVii85W79IpcmWIWOldNCL61jnFPXDLkQ',
    appId: '1:431590081010:android:ea196ee1e06488a8426b6b',
    messagingSenderId: '431590081010',
    projectId: 'lawyer-up-40365',
    storageBucket: 'lawyer-up-40365.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUtcLd9x4jC5Hgh_RHdJI4Efp6icV2Arc',
    appId: '1:431590081010:ios:c406c9fd3db8c2e2426b6b',
    messagingSenderId: '431590081010',
    projectId: 'lawyer-up-40365',
    storageBucket: 'lawyer-up-40365.appspot.com',
    iosClientId: '431590081010-ul3kt64qv74nd4s6m92vrrhdbkr9n0ig.apps.googleusercontent.com',
    iosBundleId: 'com.example.lawyerup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUtcLd9x4jC5Hgh_RHdJI4Efp6icV2Arc',
    appId: '1:431590081010:ios:c406c9fd3db8c2e2426b6b',
    messagingSenderId: '431590081010',
    projectId: 'lawyer-up-40365',
    storageBucket: 'lawyer-up-40365.appspot.com',
    iosClientId: '431590081010-ul3kt64qv74nd4s6m92vrrhdbkr9n0ig.apps.googleusercontent.com',
    iosBundleId: 'com.example.lawyerup',
  );
}
